### ISSUE TITLE
Unable to create/find/resolve database user

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#149]
Windows 10 (windows update is current)
SQL Server 2012
Local DNN 8.0.3 package (used many times over before)

![image](https://user-images.githubusercontent.com/938023/36169732-efb0ffd6-10b1-11e8-9d76-18a2ae6b0412.png)

I don't know why this happened and I doubt you'll be able to find a way to resolve it.  I was able to work around it by unchecking the IIS App Pool setting.

**Comment by nvisionative** [comment]
Thanks @hismightiness - we'll look into it to see if this is a hard-coded or system message.  If the latter is the case, then we obviously would leave that alone.

**Comment by hismightiness** [comment]
This is now happening to me on SQL 2016 as well.  I'm no longer able to create sites unless I uncheck the app pool setting, but even then it sometimes still throws the error - almost randomly it feels.  :(

**Comment by hismightiness** [comment]
Although I have a new symptom... I can't get past the installation wizard when using nvQuickSite now.  The DB installation step throws the following exception.

0:56 Minutes   |   18% ERROR occured - System.Data.SqlClient.SqlException (0x80131904): Cannot find the user 'WORKGROUP\MYCOMPUTERNAME$', because it does not exist or you do not have permission.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:304a483c-14c3-4c49-be7e-8e8c474de2fc
 Error Number:15151,State:1,Class:16
 
 DECLARE @command nvarchar(4000)
 
 SET @command = 'GRANT EXECUTE ON [dbo].aspnet_RegisterSchemaVersion TO ' + QUOTENAME(user)
 EXEC (@command)
 
 System.Data.SqlClient.SqlException (0x80131904): Cannot find the user 'WORKGROUP\MYCOMPUTERNAME1$', because it does not exist or you do not have permission.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:304a483c-14c3-4c49-be7e-8e8c474de2fc
 Error Number:15151,State:1,Class:16
 
 DECLARE @command nvarchar(400)
 SET @command = 'GRANT EXECUTE ON [dbo].aspnet_AnyDataInTables TO ' + QUOTENAME(user)
 EXEC (@command)
 
 System.Data.SqlClient.SqlException (0x80131904): Cannot find the user 'WORKGROUP\MYCOMPUTERNAME$', because it does not exist or you do not have permission.
 Creating the vw_aspnet_Applications view...
 Creating the vw_aspnet_Users view...
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:304a483c-14c3-4c49-be7e-8e8c474de2fc
 Error Number:15151,State:1,Class:16
 
 /*************************************************************/
 /*************************************************************/
 
 IF (NOT EXISTS (SELECT name
 FROM sys.objects
 WHERE (name = N'vw_aspnet_Applications')
 AND (type = 'V')))
 BEGIN
 PRINT 'Creating the vw_aspnet_Applications view...'
 EXEC('
 CREATE VIEW [dbo].[vw_aspnet_Applications]
 AS SELECT [ApplicationName], [LoweredApplicationName], [ApplicationId], [Description]
 FROM [dbo].[aspnet_Applications]
 ')
 END
 
 /*************************************************************/
 /*************************************************************/
 
 IF (NOT EXISTS (SELECT name
 FROM sys.objects
 WHERE (name = N'vw_aspnet_Users')
 AND (type = 'V')))
 BEGIN
 PRINT 'Creating the vw_aspnet_Users view...'
 EXEC('
 CREATE VIEW [dbo].[vw_aspnet_Users]
 AS SELECT [ApplicationId], [UserId], [UserName], [LoweredUserName], [MobileAlias], [IsAnonymous], [LastActivityDate]
 FROM [dbo].[aspnet_Users]
 ')
 END
 
 /*************************************************************/
 /*************************************************************/
 DECLARE @command nvarchar(4000)
 
 SET @command = 'REVOKE EXECUTE ON [dbo].aspnet_RegisterSchemaVersion from ' + QUOTENAME(user)
 EXEC (@command)
 
 System.Data.SqlClient.SqlException (0x80131904): Cannot find the user 'WORKGROUP\MYCOMPUTERNAME$', because it does not exist or you do not have permission.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:304a483c-14c3-4c49-be7e-8e8c474de2fc
 Error Number:15151,State:1,Class:16
 
 /*************************************************************/
 /*************************************************************/
 
 --
 --Create Membership schema version
 --
 DECLARE @command nvarchar(4000)
 SET @command = 'GRANT EXECUTE ON [dbo].aspnet_RegisterSchemaVersion TO ' + QUOTENAME(user)
 EXECUTE (@command)
 
 System.Data.SqlClient.SqlException (0x80131904): The specified schema name "WORKGROUP\MYCOMPUTERNAME$" either does not exist or you do not have permission to use it.
 The specified schema name "WORKGROUP\MYCOMPUTERNAME$" either does not exist or you do not have permission to use it.
 The specified schema name "WORKGROUP\MYCOMPUTERNAME$" either does not exist or you do not have permission to use it.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:304a483c-14c3-4c49-be7e-8e8c474de2fc
 Error Number:2760,State:1,Class:16
 
 /*************************************************************/
 /*************************************************************/
 
 --
 --Create Membership roles
 --
 
 IF ( NOT EXISTS ( SELECT name
 FROM sys.database_principals
 WHERE [type] = 'R'
 AND name = N'aspnet_Membership_FullAccess' ) )
 CREATE ROLE aspnet_Membership_FullAccess
 
 IF ( NOT EXISTS ( SELECT name
 FROM sys.database_principals
 WHERE [type] = 'R'
 AND name = N'aspnet_Membership_BasicAccess' ) )
 CREATE ROLE aspnet_Membership_BasicAccess
 
 IF ( NOT EXISTS ( SELECT name
 FROM sys.database_principals
 WHERE [type] = 'R'
 AND name = N'aspnet_Membership_ReportingAccess' ) )
 CREATE ROLE aspnet_Membership_ReportingAccess
 
 System.Data.SqlClient.SqlException (0x80131904): User or role 'aspnet_Membership_FullAccess' does not exist in this database.
 User or role 'aspnet_Membership_FullAccess' does not exist in this database.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:304a483c-14c3-4c49-be7e-8e8c474de2fc
 Error Number:15410,State:1,Class:11
 
 EXEC sp_addrolemember N'aspnet_Membership_BasicAccess', N'aspnet_Membership_FullAccess'
 EXEC sp_addrolemember N'aspnet_Membership_ReportingAccess', N'aspnet_Membership_FullAccess'
 
 System.Data.SqlClient.SqlException (0x80131904): Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission.
 Cannot find the user 'WORKGROUP\MYCOMPUTERNAME$', because it does not exist or you do not have permission.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:304a483c-14c3-4c49-be7e-8e8c474de2fc
 Error Number:15151,State:1,Class:16
 
 --
 --Stored Procedure rights for BasicAcess
 --
 GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByUserId TO aspnet_Membership_BasicAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByName TO aspnet_Membership_BasicAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByEmail TO aspnet_Membership_BasicAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_GetPassword TO aspnet_Membership_BasicAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_GetPasswordWithFormat TO aspnet_Membership_BasicAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_UpdateUserInfo TO aspnet_Membership_BasicAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_GetNumberOfUsersOnline TO aspnet_Membership_BasicAccess
 GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO aspnet_Membership_BasicAccess
 GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO aspnet_Membership_BasicAccess
 GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO aspnet_Membership_BasicAccess
 
 --
 --Stored Procedure rights for ReportingAccess
 --
 GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByUserId TO aspnet_Membership_ReportingAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByName TO aspnet_Membership_ReportingAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByEmail TO aspnet_Membership_ReportingAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_GetAllUsers TO aspnet_Membership_ReportingAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_GetNumberOfUsersOnline TO aspnet_Membership_ReportingAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_FindUsersByName TO aspnet_Membership_ReportingAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_FindUsersByEmail TO aspnet_Membership_ReportingAccess
 GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO aspnet_Membership_ReportingAccess
 GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO aspnet_Membership_ReportingAccess
 GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO aspnet_Membership_ReportingAccess
 
 --
 --Additional stored procedure rights for FullAccess
 --
 GRANT EXECUTE ON dbo.aspnet_Users_DeleteUser TO aspnet_Membership_FullAccess
 
 GRANT EXECUTE ON dbo.aspnet_Membership_CreateUser TO aspnet_Membership_FullAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_SetPassword TO aspnet_Membership_FullAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_ResetPassword TO aspnet_Membership_FullAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_UpdateUser TO aspnet_Membership_FullAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_ChangePasswordQuestionAndAnswer TO aspnet_Membership_FullAccess
 GRANT EXECUTE ON dbo.aspnet_Membership_UnlockUser TO aspnet_Membership_FullAccess
 
 --
 --View rights
 --
 GRANT SELECT ON dbo.vw_aspnet_Applications TO aspnet_Membership_ReportingAccess
 GRANT SELECT ON dbo.vw_aspnet_Users TO aspnet_Membership_ReportingAccess
 
 GRANT SELECT ON dbo.vw_aspnet_MembershipUsers TO aspnet_Membership_ReportingAccess
 
 /*************************************************************/
 /*************************************************************/
 /*************************************************************/
 /*************************************************************/
 
 DECLARE @command nvarchar(4000)
 SET @command = 'REVOKE EXECUTE ON [dbo].aspnet_RegisterSchemaVersion FROM ' + QUOTENAME(user)
 EXECUTE (@command)

**Comment by hismightiness** [comment]
The only way I can get a site to install successfully now is to go into SSMS to manually assign an existing user to the DBO for the DB, and then update the web.config appropriately, before I click the button to view the site.

**Comment by hismightiness** [comment]
This doesn't appear to be an issue once I uninstall the previous version of nvQuickSite and then install and use version 1.2.

**Comment by nvisionative** [comment]
@hismightiness that is great news!  We felt like we may have fixed this issue as a side effect of resolving another issue, but we were not 100% sure how to recreate and test.  Thanks for confirming.  We will mark this issue as closed.
