### ISSUE TITLE
Some or all identity references could not be translated

### ISSUE THREAD

**Issue by andrewdemos** [nvisionative/nvQuickSite#321]
Hi there!

I have reviewed previous issues relating to the "Some or all identity references could not be translated" error, but I'm stuck.

Can someone provide tips on how to work around, or troubleshoot the issue?

2021-06-11 09:38:31.131 -04:00 [ERR] Error occured while attempting to set folder permissions
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.ObjectSecurity.ModifyAccessRule(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at nvQuickSite.Controllers.FileSystemController.SetFolderPermission(String accountName, String folderPath)

Thanks!

Andrew de Mos

**Comment by david-poindexter** [comment]
@andrewdemos are you by chance trying to do this within your user documents folder structure?  If so, I'd try it outside of that folder structure (due to special permissions that could be getting in the way there).

Do you have antivirus software installed (e.g., Kaspersky)?  If so, try doing this again with it temporarily disabled - just to see if it is getting in the way.

Lastly, I'd recommend enabling a higher level of logging in nvQuickSite to see if that shows any more clues.

**Comment by andrewdemos** [comment]
Hi David,

I am setting up a site in the default folder (C:\inetpub\wwwroot), and do not have any anti-virus running other than the standard windows Defender.

After switching from using (local) to the default named instance, I'm now seeing a different error:

2021-06-11 14:04:32.241 -04:00 [ERR] Error creating database sand1www
System.Data.SqlClient.SqlException (0x80131904): The CREATE DATABASE statement failed. The primary file must be at least 1024 MB to accommodate a copy of the model database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at nvQuickSite.Controllers.DatabaseController.CreateDatabase()
ClientConnectionId:ee37b7fa-ea85-458d-9c56-6053a5e7d82d
Error Number:1803,State:1,Class:16

Any suggestions on how to address that?

Thanks very much for your help!

Andrew

**Comment by david-poindexter** [comment]
Okay, sounds like a permissions issue with the user for the creation of the database.  The `CreateDatabase` requires access to the `master` database for the SQL Server instance.  Are you using `SQL Server Authentication` or `Windows Authentication`?

**Comment by andrewdemos** [comment]
Windows Authentication

**Comment by andrewdemos** [comment]
Unfortunately, I'm able to create a new database using my Domain account - but not when running nvQuickSite.  How does "NT Service\MSSQLSERVER" get used when creating a database?  Could the default instance be playing a factor in the error thrown?

**Comment by david-poindexter** [comment]
Here is the code that creates a database:
https://github.com/nvisionative/nvQuickSite/blob/41494e3a0baba7fe443cd37c83ecc880fbf9ec46/nvQuickSite/Controllers/DatabaseController.cs#L128-L178 

Can you try using your SQL Server `sa` account from within nvQuickSite and see if that has a problem too?

Also, did you increase your logging level in nvQuickSite settings and see if anything in the logs would help point to the underlying issue?

**Comment by andrewdemos** [comment]
Hi David,

I get a CREATE DATABASE error after enabling sa as well:

2021-06-15 08:30:35.216 -04:00 [ERR] Error creating database sand1www
System.Data.SqlClient.SqlException (0x80131904): The CREATE DATABASE statement failed. The primary file must be at least 1024 MB to accommodate a copy of the model database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at nvQuickSite.Controllers.DatabaseController.CreateDatabase()
ClientConnectionId:28f8601a-7915-45cb-916e-2944ddca8734
Error Number:1803,State:1,Class:16

Andrew

**Comment by andrewdemos** [comment]
Hi David - just a quick update.  It turns out that the database had indeed been set up with a 1,024 MB model database (as opposed to the usual ~10 MB) - so that was a valid error message!  I have now resized the model database, and nvQuickSite is working!

Thanks very much for your help!

Andrew

**Comment by david-poindexter** [comment]
@andrewdemos oh wow - that is good to know and I am glad to hear you got it all working!  Enjoy **nvQuickSite** - it's a huge timesaver once you get your environment prereqs in place!  😃👍🏼

**Comment by andrewdemos** [comment]
Thanks, David - I thought I'd leave you with an idea to check that the database sizing fits with what's done (attempted) in the create database function.  Thanks again!

**Comment by david-poindexter** [comment]
Thanks @andrewdemos - if you'd like to log that idea as a separate issue, perhaps someone could pick it up as a new contribution.  Off the top of my head, I'm not sure exactly what's possible or not in this area.
