### ISSUE TITLE
Unable to Install a New Site Due to Folder Permissions

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#334]
I just upgraded to the latest release, 2.1.1.  In previous versions, I had no issues installing on this same computer.  I just stepped through the wizard like magic.  In this release, I get to the end and receive a previously unseen error message about not being able to set the permissions of the local folder (see screenshot below).  I've included the log of the issue as well.  

![image](https://user-images.githubusercontent.com/938023/132373864-a84ce7d8-dbcb-40c5-aa2c-d473f349b6b3.png)  

```  
2021-09-07 08:39:14.846 -07:00 [INF] Saved user settings
2021-09-07 08:41:16.483 -07:00 [INF] Creating site platform9101.loc in C:\Work\Platform\platform9101
2021-09-07 08:41:16.509 -07:00 [INF] Site platform9101.loc was deleted
2021-09-07 08:41:17.036 -07:00 [INF] Created site platform9101.loc
2021-09-07 08:41:17.048 -07:00 [INF] platform9101.loc already in C:\WINDOWS\system32\drivers\etc\hosts
2021-09-07 08:41:17.048 -07:00 [INF] Creating file system directories for platform9101.loc
2021-09-07 08:41:17.049 -07:00 [INF] Deleting directory C:\Work\Platform\platform9101\Website
2021-09-07 08:41:17.051 -07:00 [ERR] Error occured while attempting to set folder permissions
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.ObjectSecurity.ModifyAccessRule(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at nvQuickSite.Controllers.FileSystemController.SetFolderPermission(String accountName, String folderPath)
```

**Comment by hismightiness** [comment]
You're going to love this...  I tried several times, including a few more than usual to help report an idea and this issue.  I got done doing that and just clicked the button again - just for the heck of it...  

It's working again all of a sudden!  😆 🤣 🤦🏽‍♂️

**Comment by david-poindexter** [comment]
Just a theory here, but could the local website that you were replacing have been accessed within the 20-minute period prior to the new installation attempt?  I am wondering if there was a locked file and/or database connection.  These kinds of issues are really hard to address due to their seemingly random nature and our inability to reproduce them at will.  That said, we know some tender love and care could be given to the areas leveraging Windows identities for system I/O work. 

If this is something that you see on a regular basis moving forward, let me know and I'll be happy to help you get the project setup locally for a deeper code debugging session.  It would be awesome to find these gremlins in these areas of the code that obviously need some attention and greater flexibility for different user environments.

**Comment by hismightiness** [comment]
In this case, I hadn't yet used that path & version on this computer, so it's not likely a locked file (due to previous access, at least).  

Since these kinds of oddities might happen a lot and for various reasons, it might be useful to have a debug/logging feature that adds more details to the log file.  🤷🏽‍♂️

**Comment by david-poindexter** [comment]
According to the log entries you shared, that site and folder already existed.

```
2021-09-07 08:41:16.483 -07:00 [INF] Creating site platform9101.loc in C:\Work\Platform\platform9101
2021-09-07 08:41:16.509 -07:00 [INF] Site platform9101.loc was deleted
2021-09-07 08:41:17.036 -07:00 [INF] Created site platform9101.loc
2021-09-07 08:41:17.048 -07:00 [INF] platform9101.loc already in C:\WINDOWS\system32\drivers\etc\hosts
2021-09-07 08:41:17.048 -07:00 [INF] Creating file system directories for platform9101.loc
2021-09-07 08:41:17.049 -07:00 [INF] Deleting directory C:\Work\Platform\platform9101\Website
```

As far as logging levels, these are already possible via nvQuickSiteSettings.

![image](https://user-images.githubusercontent.com/4568451/132379647-8f17da85-aab9-4160-a0dd-348ff10c402f.png)

Switching to "Verbose" will give you the greatest level of logging.

**Comment by hismightiness** [comment]
Yes, in that instance, it already existed, but only because it was like the 5th time clicking the button.  😄 

I didn't know about the verbose option.  I'll try to remember that next time.  Thanks!  :)
