### ISSUE TITLE
Error Extracting Zip File

### ISSUE THREAD

**Issue by WillStrohl** [nvisionative/nvQuickSite#376]
First and foremost, the SSL update is epic!!!  Thank you!  

## Background  

I'm on a new computer, but the same steps below worked before the recent updates to nvQuickSite.  I've been running everything fine for almost two months now.  🤷🏽‍♂️ 

Kaspersky is trusting nvQuickSite already.  See below.  

![image](https://user-images.githubusercontent.com/938023/217411926-98ab461e-5fcc-416b-ad7a-07038c652354.png)

However, I still had to dive into the settings to manually allow the EXE to be able to edit the HOSTS file before I could do it again.  I think Kaspersky might have new features that are getting in the way.  The trust setting didn't allow this anymore.  

![image](https://user-images.githubusercontent.com/938023/217412855-bad53672-ef03-4e75-9b3e-3698e2739ddb.png)  

### Related Detail  

When I tried by using the download feature, it worked.  However, I'd prefer to not have to download it every time.  

The local zip files I use are not in a protected folder of any kind.  It's a local folder, like below.  

`C:\Work\Platform\DNN_Platform_9.11.0_Install.zip`  

## Steps to Reproduce  

- nvQuickSite:  2.3.3  
- OS:  Windows 11 Pro  

When I start it, I select a local zip file (the same I've been using since before the upgrades).  

Next, I follow the wizard until it's time to extract the zip file.  When I get there I get the following errors.  

![image](https://user-images.githubusercontent.com/938023/217412213-4a298d53-a2b2-42f7-a1a6-83e049dea7c3.png)

![image](https://user-images.githubusercontent.com/938023/217412233-2ea3a32f-4a45-4e38-aa16-f31fd895d0b2.png)

Just in case it might be the zip file, I tried another one (again, one I know worked before the upgrades), and I get a completely different error now.  

![image](https://user-images.githubusercontent.com/938023/217412319-0f320188-b8a7-4533-9154-d9874ebf8dd9.png)

Here are what I believe are the relevant errors from the log file.  

```  
2023-02-07 18:08:48.583 -08:00 [ERR] Error attempting to read and extract the package
Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException: Could not read block - no data!  (position 0x00055A62)
   at Ionic.Zip.SharedUtilities._ReadFourBytes(Stream s, String message)
   at Ionic.Zip.ZipEntry.HandleUnexpectedDataDescriptor(ZipEntry entry)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile.Read(String fileName, TextWriter statusMessageWriter, Encoding encoding, EventHandler`1 readProgress)
   at nvQuickSite.Start.ReadAndExtract(String openPath, String savePath)  

System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.ObjectSecurity.ModifyAccessRule(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at nvQuickSite.Controllers.FileSystemController.SetFolderPermission(String accountName, String folderPath) 

2023-02-07 18:17:49.503 -08:00 [ERR] Error occured while attempting to set permissions for IIS APPPOOL\platform972.loc_nvQuickSite on folder C:\Work\Platform\platform972\Website
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.ObjectSecurity.ModifyAccessRule(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at nvQuickSite.Controllers.FileSystemController.SetFolderPermission(String accountName, String folderPath)  
```

**Comment by valadas** [comment]
Not sure if it helps this issue, but we could probably remove Ionic.Zip in favor of the standard .net zip buil-in support. One less dependency.

**Comment by WillStrohl** [comment]
@david-poindexter Yep. The additional permissions to `Create` and `Delete` seemed to be necessary now.  🤷🏽‍♂️

**Comment by david-poindexter** [comment]
> @david-poindexter Yep. The additional permissions to `Create` and `Delete` seemed to be necessary now. 🤷🏽‍♂️

Awesome glad that worked for you.  I fought with that for hours!  😆
